// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI tools (migrate, push, studio) use `url` — must be a direct connection
    // because migrations run DDL commands that don't work through a pooler.
    url: process.env["DIRECT_URL"],
  },
});
